title: Proyecto Mumuki
email: mumuki-dev@googlegroups.com
description: >
  Sitio institucional en español del Proyecto Mumuki,
  el proyecto colectivo de brindar educación de
  calidad, libre y gratuita sobre programación.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mumuki.org"
twitter_username: MumukiPlatform
github_username:  mumuki

# Build settings
markdown: kramdown
